<?php
/* @var $block \Mailjet\Mailjet\Block\Adminhtml\System\Config\Fieldset\Button\Resync */
/* @var  $escaper \Magento\Framework\Escaper */

//phpcs:disable
use Mailjet\Mailjet\Helper\Data;

?>
<?= $block->getButtonHtml() ?>
<script type="text/javascript">//<![CDATA[
    require([
        'prototype',
        'jquery'
    ], function () {
        Event.observe('<?= $block->escapeHtml(Data::FIELD_ID_ACCOUNT_SYNC_RESYNC_BUTTON); ?>', 'click', function () {
            var mailjet_resync_button_id = '<?= $block->escapeHtml(Data::FIELD_ID_ACCOUNT_SYNC_RESYNC_BUTTON); ?>';
            var mailjet_api_key_id = '<?= $block->escapeHtml(Data::FIELD_ID_ACCOUNT_API_KEY); ?>';
            var mailjet_secret_key_id = '<?= $block->escapeHtml(Data::FIELD_ID_ACCOUNT_SECRET_KEY); ?>';
            var mailjet_list_id = '<?= $block->escapeHtml(Data::FIELD_ID_ACCOUNT_MAILJET_LIST); ?>';
            var mailjet_sync_preference_id = '<?= $block->escapeHtml(Data::FIELD_ID_ACCOUNT_SYNC_PREFERENCE); ?>';
            var mailjet_ecommerce_data_id = '<?= $block->escapeHtml(Data::FIELD_ID_ECOMMERCE_DATA); ?>';
            var mailjet_resync_button = jQuery('#' + mailjet_resync_button_id);
            var mailjet_api_key = jQuery('#' + mailjet_api_key_id);
            var mailjet_secret_key = jQuery('#' + mailjet_secret_key_id);
            var mailjet_list = jQuery('#' + mailjet_list_id);
            var mailjet_sync_preference = jQuery('#' + mailjet_sync_preference_id);
            var mailjet_ecommerce_data = jQuery('#' + mailjet_ecommerce_data_id);

            mailjet_list.trigger('processStart');

            jQuery.ajax({
                url: '<?= $escaper->escapeUrl($block->getUrl('mailjet/system_config/resync')); ?>',
                data: {
                    website_id: '<?= /* @noEscape */$block->getRequest()->getParam('website'); ?>',
                    api_key: mailjet_api_key.val(),
                    secret_key: mailjet_secret_key.val(),
                    list: mailjet_list.val(),
                    sync_preference: mailjet_sync_preference.val(),
                    ecommerce_data: mailjet_ecommerce_data.val(),
                },
                type: 'POST',
                success: function(data) {
                    jQuery('#' + mailjet_resync_button_id + '-error').remove();

                    if (!data.result) {
                        jQuery('<label class="mage-error" id="' + mailjet_resync_button_id + '-error">' + data.mailjet_error + '</label>').insertAfter('#' + mailjet_resync_button_id);
                    }

                    mailjet_list.trigger('processStop');
                }
            });
        });

        Event.observe('<?= $block->escapeHtml(Data::FIELD_ID_ACCOUNT_SYNC_PREFERENCE); ?>', 'change', function (element) {
            if (jQuery(element.srcElement).val() == "<?= $block->escapeHtml(Data::SYNC_PREFERENCE_ONLY_FUTURE); ?>") {
                jQuery('#<?= $block->escapeHtml(Data::FIELD_ID_ACCOUNT_SYNC_RESYNC_BUTTON); ?>').attr('disabled', 'disabled');
            } else {
                jQuery('#<?= $block->escapeHtml(Data::FIELD_ID_ACCOUNT_SYNC_RESYNC_BUTTON); ?>').removeAttr('disabled');
            }
        });

        document.getElementById('<?= $block->escapeHtml(Data::FIELD_ID_ACCOUNT_SYNC_PREFERENCE); ?>').dispatchEvent(new Event('change'));
    });
//]]></script>
<?php //phpcs:enable ?>
