<?php
// phpcs:disable
/* @var $block \Mailjet\Mailjet\Block\Adminhtml\System\Config\Fieldset\ValidateCredentials */
/* @var  $escaper \Magento\Framework\Escaper */

?>

<script type="text/javascript">//<![CDATA[
    require([
        'prototype',
        'jquery',
        'mage/mage',
        'jquery/validate', // Jquery Validation Library
        'mage/translate' // Magento text translate (Validation message translte as per language)
    ], function () {
        var checkCredentials = function(el) {
            var mailjet_api_key_id = '<?= \Mailjet\Mailjet\Helper\Data::FIELD_ID_ACCOUNT_API_KEY; ?>';
            var mailjet_secret_key_id = '<?= \Mailjet\Mailjet\Helper\Data::FIELD_ID_ACCOUNT_SECRET_KEY; ?>';
            var mailjet_list_id = '<?= \Mailjet\Mailjet\Helper\Data::FIELD_ID_ACCOUNT_MAILJET_LIST; ?>';
            var mailjet_api_key = jQuery('#' + mailjet_api_key_id);
            var mailjet_secret_key = jQuery('#' + mailjet_secret_key_id);
            var mailjet_list = jQuery('#' + mailjet_list_id);

            mailjet_api_key.valid();
            mailjet_secret_key.valid();
            jQuery(el.target).trigger('processStart');

            jQuery.ajax({
                url: '<?= $escaper->escapeUrl($block->getUrl('mailjet/system_config/validatecredentials')); ?>',
                data: {
                    api_key: mailjet_api_key.val(),
                    secret_key: mailjet_secret_key.val(),
                    website_id: '<?= /* @noEscape */$block->getRequest()->getParam('website'); ?>',
                    store_id: '<?= /* @noEscape */ $block->getRequest()->getParam('store'); ?>'
                },
                type: 'POST',
                success: function(data) {
                    mailjet_list.html('');

                    if (data.result) {
                        data.mailjet_list.forEach(function(option) {
                            mailjet_list.append(jQuery('<option>', {
                                value: option.value,
                                text: option.label
                            }));
                        });
                        document.getElementById(mailjet_list_id).dispatchEvent(new Event('change'));
                    } else {
                        mailjet_api_key.addClass('mage-error');
                        mailjet_secret_key.addClass('mage-error');
                        jQuery('<label for="' + mailjet_secret_key_id + '" class="mage-error" id="' + mailjet_secret_key_id + '-error">' + jQuery.mage.__('The API key and Secret key don\'t match. Please make sure that you are using the correct API key and Secret key associated to your Mailjet account.') + '</label>').insertAfter(mailjet_secret_key);
                    }

                    jQuery(el.target).trigger('processStop');
                }
            });
        }

        Event.observe('<?= \Mailjet\Mailjet\Helper\Data::FIELD_ID_ACCOUNT_API_KEY; ?>', 'change', checkCredentials);
        Event.observe('<?= \Mailjet\Mailjet\Helper\Data::FIELD_ID_ACCOUNT_SECRET_KEY; ?>', 'change', checkCredentials);
    });
//]]></script>
<?php  // phpcs:enable ?>
